import oracledb

from src.database.db import get_connection


CREATE_TABLE_SQL = """
CREATE TABLE LOL_CHAMPIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    riot_id VARCHAR2(100) NOT NULL,
    champion_key VARCHAR2(20) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    title VARCHAR2(200),
    primary_tag VARCHAR2(50),
    secondary_tag VARCHAR2(50),
    partype VARCHAR2(50),
    version VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_lol_champions_riot_id UNIQUE (riot_id)
)
"""


def create_table():
    connection = None
    cursor = None

    try:
        connection = get_connection()
        cursor = connection.cursor()

        cursor.execute(
            CREATE_TABLE_SQL
        )

        connection.commit()

        print(
            "Tabela LOL_CHAMPIONS criada com sucesso."
        )

    except oracledb.DatabaseError as error:
        error_obj = error.args[0]

        if error_obj.code == 955:
            print(
                "Tabela LOL_CHAMPIONS ja existe. Nenhuma acao necessaria."
            )
            return

        print(
            "Erro ao criar a tabela LOL_CHAMPIONS:"
        )
        print(error)

        raise

    finally:
        if cursor:
            cursor.close()

        if connection:
            connection.close()


if __name__ == "__main__":
    create_table()
